// Code generated by go-bindata.
// sources:
// asset/css/grids-responsive-min.css
// asset/css/layouts/extra.css
// asset/css/layouts/side-menu.css
// asset/css/pure-LICENSE.md
// asset/css/pure-min.css
// asset/js/app.js
// asset/js/ui.js
// asset/pages/configuration.html
// asset/pages/containers.html
// asset/pages/doc.html
// asset/pages/index.html
// asset/pages/machine.html
// asset/pages/machines.html
// asset/pages/menu.html
// asset/pages/node.html
// asset/pages/system.html
// DO NOT EDIT!

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// assetCssGridsResponsiveMinCss reads file data from disk. It returns an error on failure.
func assetCssGridsResponsiveMinCss() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/css/grids-responsive-min.css"
	name := "asset/css/grids-responsive-min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetCssLayoutsExtraCss reads file data from disk. It returns an error on failure.
func assetCssLayoutsExtraCss() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/css/layouts/extra.css"
	name := "asset/css/layouts/extra.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetCssLayoutsSideMenuCss reads file data from disk. It returns an error on failure.
func assetCssLayoutsSideMenuCss() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/css/layouts/side-menu.css"
	name := "asset/css/layouts/side-menu.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetCssPureLicenseMd reads file data from disk. It returns an error on failure.
func assetCssPureLicenseMd() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/css/pure-LICENSE.md"
	name := "asset/css/pure-LICENSE.md"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetCssPureMinCss reads file data from disk. It returns an error on failure.
func assetCssPureMinCss() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/css/pure-min.css"
	name := "asset/css/pure-min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetJsAppJs reads file data from disk. It returns an error on failure.
func assetJsAppJs() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/js/app.js"
	name := "asset/js/app.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetJsUiJs reads file data from disk. It returns an error on failure.
func assetJsUiJs() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/js/ui.js"
	name := "asset/js/ui.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesConfigurationHtml reads file data from disk. It returns an error on failure.
func assetPagesConfigurationHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/configuration.html"
	name := "asset/pages/configuration.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesContainersHtml reads file data from disk. It returns an error on failure.
func assetPagesContainersHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/containers.html"
	name := "asset/pages/containers.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesDocHtml reads file data from disk. It returns an error on failure.
func assetPagesDocHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/doc.html"
	name := "asset/pages/doc.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesIndexHtml reads file data from disk. It returns an error on failure.
func assetPagesIndexHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/index.html"
	name := "asset/pages/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesMachineHtml reads file data from disk. It returns an error on failure.
func assetPagesMachineHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/machine.html"
	name := "asset/pages/machine.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesMachinesHtml reads file data from disk. It returns an error on failure.
func assetPagesMachinesHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/machines.html"
	name := "asset/pages/machines.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesMenuHtml reads file data from disk. It returns an error on failure.
func assetPagesMenuHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/menu.html"
	name := "asset/pages/menu.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesNodeHtml reads file data from disk. It returns an error on failure.
func assetPagesNodeHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/node.html"
	name := "asset/pages/node.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetPagesSystemHtml reads file data from disk. It returns an error on failure.
func assetPagesSystemHtml() (*asset, error) {
	path := "/root/astralboot/src/astralboot/asset/pages/system.html"
	name := "asset/pages/system.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"asset/css/grids-responsive-min.css": assetCssGridsResponsiveMinCss,
	"asset/css/layouts/extra.css": assetCssLayoutsExtraCss,
	"asset/css/layouts/side-menu.css": assetCssLayoutsSideMenuCss,
	"asset/css/pure-LICENSE.md": assetCssPureLicenseMd,
	"asset/css/pure-min.css": assetCssPureMinCss,
	"asset/js/app.js": assetJsAppJs,
	"asset/js/ui.js": assetJsUiJs,
	"asset/pages/configuration.html": assetPagesConfigurationHtml,
	"asset/pages/containers.html": assetPagesContainersHtml,
	"asset/pages/doc.html": assetPagesDocHtml,
	"asset/pages/index.html": assetPagesIndexHtml,
	"asset/pages/machine.html": assetPagesMachineHtml,
	"asset/pages/machines.html": assetPagesMachinesHtml,
	"asset/pages/menu.html": assetPagesMenuHtml,
	"asset/pages/node.html": assetPagesNodeHtml,
	"asset/pages/system.html": assetPagesSystemHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"asset": &bintree{nil, map[string]*bintree{
		"css": &bintree{nil, map[string]*bintree{
			"grids-responsive-min.css": &bintree{assetCssGridsResponsiveMinCss, map[string]*bintree{}},
			"layouts": &bintree{nil, map[string]*bintree{
				"extra.css": &bintree{assetCssLayoutsExtraCss, map[string]*bintree{}},
				"side-menu.css": &bintree{assetCssLayoutsSideMenuCss, map[string]*bintree{}},
			}},
			"pure-LICENSE.md": &bintree{assetCssPureLicenseMd, map[string]*bintree{}},
			"pure-min.css": &bintree{assetCssPureMinCss, map[string]*bintree{}},
		}},
		"js": &bintree{nil, map[string]*bintree{
			"app.js": &bintree{assetJsAppJs, map[string]*bintree{}},
			"ui.js": &bintree{assetJsUiJs, map[string]*bintree{}},
		}},
		"pages": &bintree{nil, map[string]*bintree{
			"configuration.html": &bintree{assetPagesConfigurationHtml, map[string]*bintree{}},
			"containers.html": &bintree{assetPagesContainersHtml, map[string]*bintree{}},
			"doc.html": &bintree{assetPagesDocHtml, map[string]*bintree{}},
			"index.html": &bintree{assetPagesIndexHtml, map[string]*bintree{}},
			"machine.html": &bintree{assetPagesMachineHtml, map[string]*bintree{}},
			"machines.html": &bintree{assetPagesMachinesHtml, map[string]*bintree{}},
			"menu.html": &bintree{assetPagesMenuHtml, map[string]*bintree{}},
			"node.html": &bintree{assetPagesNodeHtml, map[string]*bintree{}},
			"system.html": &bintree{assetPagesSystemHtml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

